### ISSUE TITLE
Add share button that would just copy the URL to the clipboard

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#187]
![Screenshot 2024-05-19 at 10 07 19 PM](https://github.com/nih-cfde/playbook-partnership/assets/12749033/f8589ad5-b0a1-408d-a4a8-844f17879481)

**Comment by u8sand** [comment]
Several questions I have related to this change @AviMaayan 

- Currently, we use the "share" icon for publishing, I don't think we should use the same icon for a different function, so I suggest using the link icon or alternatively finding a different "publish" icon. Please advise
![image](https://github.com/MaayanLab/Playbook-Workflow-Builder/assets/1341861/77a72b08-ad7e-437e-8a45-f77a384d5051)
- Currently, we only give you the link to the playbook if you have it saved, this is because unsaved playbooks are subject to deletion and thus a user might arrive at a 404 if it was deleted since the playbook was shared. We can either: auto-save when you click the share button (you would need to be logged in for this), or just give the link ignoring this potential issue.

**Comment by AviMaayan** [comment]
I forgot about this policy... I like the idea of saving automatically if the user presses the share button. As a naive user, I created the GTEx workflow and then wanted to share it with you to report a bug, so it was not trivial to me that I need to save the workflow first...
