### ISSUE TITLE
The "upload file" card is a bit too generic, can it be changes to upload an "expression matrix"

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#76]

**Comment by u8sand** [comment]
Since we have several different types of files that can be uploaded
![image](https://github.com/nih-cfde/playbook-partnership/assets/1341861/e166735e-34f1-4089-84a7-d3a521b0b60b)

just changing file upload to gene expression matrix will be problematic.
I'm working on turning the upload component into a "factory helper" then all of these different file types will just appear at the start, reusing a similar upload interface & API helpers

**Comment by AviMaayan** [comment]
Perfect!
