### ISSUE TITLE
Enter drug name (warfarin) but the Enrichr term search did not work for this drug

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/playbook-partnership#93]
https://playbook-workflow-builder.cloud/graph/1cd19811-6766-c46d-64c7-5928d71a4c86/node/33d371f7-467b-8007-0ad3-c61e4d38422b

**Comment by u8sand** [comment]
The drug term was not submitted, that's why it also doesn't show up in the story.. this will be more obviously indicated when the progress indicator branch is merged.. 
https://playbook-workflow-builder.cloud/graph/62379967-6b12-5ae6-5821-4cfd627e3437/node/1671f34f-07af-c7c4-4218-d90ee4fe4ed8 here is with warfarin submitted
